// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppDashBoard: typeof import('./components/AppDashBoard.vue')['default']
    AppDrawer: typeof import('./components/AppDrawer.vue')['default']
    AppEditor: typeof import('./components/AppEditor.vue')['default']
    AppFileNode: typeof import("./components/AppFileNode.vue")["default"]
    AppFileNodeViewer: typeof import("./components/AppFileNodeViewer.vue")["default"]
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppFuse: typeof import('./components/AppFuse.vue')['default']
    AppLanding: typeof import('./components/AppLanding.vue')['default']
    AppMessages: typeof import('./components/AppMessages.vue')['default']
    AppNode: typeof import('./components/AppNode.vue')['default']
    AppNotifier: typeof import('./components/AppNotifier.vue')['default']
    AppPython: typeof import("./components/AppPython.vue")["default"]
    AppTerm: typeof import('./components/AppTerm.vue')['default']
    AppTree: typeof import('./components/AppTree.vue')['default']
    AppUpload: typeof import('./components/AppUpload.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VCamera: typeof import('./components/VCamera.vue')['default']
    VLogin: typeof import('./components/VLogin.vue')['default']
    VShareScreen: typeof import('./components/VShareScreen.vue')['default']
  }
}
