// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppDrawer: typeof import('./components/AppDrawer.vue')['default']
    AppEditor: typeof import('./components/AppEditor.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLanding: typeof import('./components/AppLanding.vue')['default']
    AppMessages: typeof import('./components/AppMessages.vue')['default']
    AppNotifier: typeof import('./components/AppNotifier.vue')['default']
    AppPython: typeof import('./components/AppPython.vue')['default']
    AppTree: typeof import('./components/AppTree.vue')['default']
    Dark: typeof import('./components/Dark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
